name: Jinchul's Blog
url: https://blog.supremeidea.com
description: Jinchul's Blog
keyword: programming, algorithm, development, c++, stl
markdown: kramdown
kramdown:
  input: GFM
exclude: ['images/original']
permalink: :title.html
